name: Back Build and Test
'on':
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
jobs:
  back_build_test:
    runs-on: windows-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: temurin
          server-id: github
          settings-path: '${{ github.workspace }}'
      - name: Build with Maven
        run: mvn -B package --file back/pom.xml
      - name: Test with Maven
        run: mvn -B test jacoco:report --file back/pom.xml
      - name: Upload JaCoCo report
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: ./back/target/site/jacoco