name: Front Quality Check
on:
  workflow_run:
    workflows: ["Front Build and Test"]
    branches: [main]
    types: 
      - completed
jobs:
  front_quality:
    name: SonarCloud
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Download Coverage Report
        uses: actions/download-artifact@v4
        with:
          name: "Tests coverage"
          path: ./front/coverage/
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: front
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}