name: Front test and quality workflow
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  front_build_test:
    name: Front Build and Test
    defaults:
      run:
        working-directory: front
    runs-on: windows-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 16
        uses: actions/setup-node@v4
        with:
          node-version: '16'
          cache: npm
          cache-dependency-path: 'front/package-lock.json'
      - run: npm ci
      #- name: Build the app
        #run: npm run build
      - name: Run the tests
        run: npm run test
      - name: Generate report
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: Tests coverage
          path: ./front/coverage/
          overwrite: true
          if-no-files-found: error
          
  front_quality:
    name: Front quality check
    runs-on: ubuntu-latest
    needs: front_build_test
    defaults:
      run:
        working-directory: front
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: front
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}